name: Deploy Versioned Documentation

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with 'v'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives the workflow write permission to the repository
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Checkout gh-pages branch or create if it doesn't exist
        run: |
          # Try to checkout the gh-pages branch
          git fetch origin gh-pages || true
          
          if git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
            # Branch exists, checkout
            git checkout gh-pages
          else
            # Branch doesn't exist, create orphan branch
            git checkout --orphan gh-pages
            git rm -rf .
            echo "# Documentation Versions" > index.html
            git add index.html
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Initial gh-pages commit"
          fi
      
      - name: Create version directory
        run: |
          mkdir -p ${{ env.VERSION }}
      
      - name: Copy files to version directory
        run: |
          # Checkout the tagged version to a temporary directory
          mkdir -p temp_checkout
          git clone https://github.com/${{ github.repository }}.git temp_checkout
          cd temp_checkout
          git checkout ${{ env.VERSION }}
          
          # Copy files to the version directory in the gh-pages branch
          cd ..
          cp -R temp_checkout/*.html temp_checkout/*.css temp_checkout/*.js ${{ env.VERSION }}/ 2>/dev/null || true
          cp -R temp_checkout/assets ${{ env.VERSION }}/ 2>/dev/null || true
          cp -R temp_checkout/images ${{ env.VERSION }}/ 2>/dev/null || true
          
          # Clean up
          rm -rf temp_checkout
      
      - name: Generate versions index
        run: |
          # Create/update versions.json
          echo '[' > versions.json
          
          # Get all version directories
          VERSIONS=$(find . -maxdepth 1 -type d -name "v*" | sort -Vr)
          
          # Add each version to versions.json
          FIRST=true
          for VERSION in $VERSIONS; do
            VERSION=$(basename $VERSION)
            if [ "$FIRST" = true ]; then
              echo "  {\"version\": \"$VERSION\", \"latest\": true}" >> versions.json
              FIRST=false
            else
              echo "  ,{\"version\": \"$VERSION\", \"latest\": false}" >> versions.json
            fi
          done
          
          echo ']' >> versions.json
          
          # Create/update versions index page
          cat > index.html << EOF
          <!DOCTYPE html>
          <html>
            <head>
              <title>Documentation Versions</title>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <style>
                body { font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
                h1 { color: #333; }
                ul { list-style-type: none; padding: 0; }
                li { margin: 10px 0; }
                a { color: #0366d6; text-decoration: none; }
                a:hover { text-decoration: underline; }
                .latest { font-weight: bold; }
                .latest::after { content: " (Latest)"; color: #28a745; }
              </style>
            </head>
            <body>
              <h1>Documentation Versions</h1>
              <ul id="versions-list"></ul>
              
              <script>
                fetch('./versions.json')
                  .then(response => response.json())
                  .then(versions => {
                    const list = document.getElementById('versions-list');
                    versions.forEach(version => {
                      const item = document.createElement('li');
                      const link = document.createElement('a');
                      link.href = './' + version.version + '/';
                      link.textContent = version.version;
                      if (version.latest) {
                        link.classList.add('latest');
                      }
                      item.appendChild(link);
                      list.appendChild(item);
                    });
                  });
              </script>
            </body>
          </html>
          EOF
      
      # If this is the latest version, also copy to root
      - name: Check if latest version
        id: check_latest
        run: |
          # Extract just the version numbers without the 'v' prefix for comparison
          CURRENT_VERSION=$(echo ${{ env.VERSION }} | sed 's/^v//')
          
          # Find all version directories and extract version numbers
          ALL_VERSIONS=$(find . -maxdepth 1 -type d -name "v*" | sed 's/^\.\///' | sed 's/^v//' | sort -V)
          
          # Get highest version
          HIGHEST_VERSION=$(echo "$ALL_VERSIONS" | tail -n1)
          
          # Check if current version is the highest
          if [ "$CURRENT_VERSION" = "$HIGHEST_VERSION" ]; then
            echo "IS_LATEST=true" >> $GITHUB_ENV
          else
            echo "IS_LATEST=false" >> $GITHUB_ENV
          fi
      
      - name: Copy to root if latest version
        if: env.IS_LATEST == 'true'
        run: |
          # Copy latest version files to root (excluding index.html, which we already created)
          cp -R ${{ env.VERSION }}/* . 2>/dev/null || true
          
          # Create a latest.txt file to track current latest version
          echo ${{ env.VERSION }} > latest.txt
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy documentation for version ${{ env.VERSION }}"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
